language: python

branches:
  only:
  - master

notifications:
  email: false

python:
  - 3.6

install:
  - pip install coveralls coverage termcolor

script:
  - coverage run test_rpn.py

after_success:
  - coveralls
